<?php
/** @var \Perspective\T5\Block\Template $block 
 *  @var \Perspective\T5\ViewModel\Ex1\P1 $viewModel
*/
$viewModel = $block->getViewModel();
$productId = 1;
$product = $viewModel->getProductById($productId);
$categoryIds = $product->getCategoryIds();
$categories = $viewModel->getCategoryCollection()->addAttributeToFilter('entity_id',$categoryIds);

echo '<h1>Theme 5. Ex 1.1</h1>';
echo '<h3>Get Categories from specific Product by Id = '.$productId.'</h3>';

foreach ($categories as $category) {
    echo 'Name:' . $category->getName() . '<br>';
}

?>