<?php
/**  
 *  @var \Perspective\T5\ViewModel\Ex1\P3 $viewModel
*/
$viewModel = $block->getViewModel();
$ids = [1,2,3];
$products = $viewModel->getProductCollectionByCategories($ids);

echo '<h1>Theme 5. Ex 1.3</h1>';
echo '<h3>Get Product Collection by Categories: '. implode(',', $ids).'</h3>';
foreach ($products as $product) {
    echo $product->getName() . ' - ' . $product->getProductUrl() . '<br />';
}

?>