<?php
/** @var \Perspective\RelatedProduct\Block\Template $block */

$viewModel = $block->getViewModel();
$currentProduct = $viewModel->getCurrentProduct();
//echo $currentProduct->getData('clothing_material');


$attribute = $currentProduct->getResource()->getAttribute('clothing_material');
$value = $attribute->getFrontend()->getValue($currentProduct);
$label = $attribute->getStoreLabel();

echo $label . ': ' .$value .'<br>';
