<?php
/** @var \Perspective\TutorialEntity\Block\EntityRepository $block */

?>
<?php 
$product = $block->getProductById(1);
$cheapProducts = $block->getCheapProducts(15);
?>
<div class="entity-repository">
    <h1><?=$block->getName()?></h1>
    <?php if (!is_null($product)) : ?>
        <h2><?= $product->getName(); ?></h2>
        <p><?= $product->getDescription();?></p>
    <?php endif; ?>
    <hr>
    <?php if (!is_null($cheapProducts)) : ?>
    <?php foreach ($cheapProducts as $cheapProduct): ?>
        <h2> <?= $cheapProduct->getName(); ?> </h2>
        <h3> <?= $cheapProduct->getPrice(); ?> </h3>
    <?php endforeach; ?>
    <?php endif; ?>

</div>