<?php
/** @var \Perspective\Tutor\ViewModel\Tutor $viewModel */

$viewModel = $block->getViewModel();
$product = $viewModel->getProductById(1)
?>

<div class="entity-repository">
    <h1><?=$block->getName()?></h1>
    <?php if (!is_null($product)) : ?>
        <h2><?= $product->getName(); ?></h2>
        <p><?= $product->getDescription();?></p>
    <?php endif; ?>
    <hr>
    <?php foreach ($viewModel->getCheapProducts(15) as $cheapProduct): ?>
        <h2> <?= $cheapProduct->getName(); ?> </h2>
        <h3> <?= $cheapProduct->getPrice(); ?> </h3>
    <?php endforeach; ?>
</div>