<div class="block" >
<?php 
    echo __('Users of the online store have certain rights and responsibilities when interacting with the platform. As a user, you have the right to browse products, make purchases, and expect secure payment transactions. It is your responsibility to provide accurate personal information during the registration process and to maintain the confidentiality of your account credentials.
    Users are responsible for keeping their devices and internet connections secure to prevent unauthorized access to their accounts. The online store may collect and process user data as outlined in the privacy policy, and users have the right to understand how their information is used.');
?>
</div>