<?php
/**
 * @var \Perspective\Consultations\ViewModel\Index $viewModel
 */
$viewModel = $block->getData('view_model');

$groupedData = $viewModel->getGroupedByName();
?>
<h3>Посчитать стоимость каждой консультации в зависимости от длительности Стоимость за час * Длительность. 
    При этом учесть, что консультации, проводимые с 8 до 11 утра, получают скидку, а консультация клиентам из группы Gold имеют двойную скидку. 
    Если консультация попадает под оба условия, то скидки складываются.
</h3>

<table class="data grid" data-role="grid">
    <thead>
        <tr>
            <th class="data-grid-th">Name</th>

            <th class="data-grid-th">ID</th>
            <th class="data-grid-th">Customer name</th>
            <th class="data-grid-th">Date</th>

            <th class="data-grid-th">Hours</th>
            <th class="data-grid-th">Price</th>
            <th class="data-grid-th">Subtotal</th>

            <th class="data-grid-th">Discount</th>

            <th class="data-grid-th">Group</th>
            <th class="data-grid-th">Mult.</th>
            <th class="data-grid-th">Discounted</th>
            <th class="data-grid-th">Total</th>

        </tr>
    </thead>

    <?php if ($groupedData):?>

        <tbody>
        <?php foreach ($groupedData as $group) : ?>
            <?php 
                $consCount = count($group['consultations']);    
            ?>
            
            <?php if ($consCount > 0): ?>
                <?php $isNewName = true; ?>
                <?php foreach ($group['consultations'] as $consultation) : ?>

                    <tr class="data-row" data-group="<?php echo $consultation->getData("name"); ?>">
                        <?php if ($isNewName): ?>
                            <td class="data-grid-td" rowspan="<?php echo $consCount; ?>">
                                <?php echo $consultation->getData("name"); ?>
                            </td>
                        <?php endif; ?>
                        <?php
                        $customer = $consultation->getCustomer(); 
                        $customerGr = $consultation->getCustomerGroup();
                        
                        ?>
                        <td class="data-grid-td"><?php echo $consultation->getId(); ?></td>
                        <td class="data-grid-td"><?php echo $customer->getFirstname() .' '. $customer->getLastname(); ?></td>
                        <td class="data-grid-td"><?php echo $consultation->getData("date"); ?></td>

                        <td class="data-grid-td"><?php echo $consultation->getData("hours"); ?></td>
                        <td class="data-grid-td"><?php echo $consultation->getData("price"); ?></td>
                        <td class="data-grid-td"><?php echo $consultation->getData("subtotal") ; ?></td>

                        <td class="data-grid-td"><?php echo $consultation->getData("discount")*100 . '%'; ?></td>
                        <td class="data-grid-td"><?php echo $customerGr; ?></td>
                        <td class="data-grid-td"><?php echo 'x' . $consultation->getData("multiplier"); ?></td>
                        <td class="data-grid-td"><?php echo $consultation->getData('discounted_price') ; ?></td>
                        <?php if ($isNewName): ?>
                            <td class="data-grid-td" rowspan="<?php echo $consCount; ?>">
                                <?php echo $group['total']; ?>
                            </td>
                            <?php $isNewName = false; ?>
                        <?php endif; ?>
                        

                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <?php continue;?>
            <?php endif; ?>
        <?php endforeach; ?>

        </tbody>
    <?php endif;?>

</table>

